# [agent] test deprecated: Feature12 CLI registry tests are superseded by feature13 tests.
# def test_publish_cli_usage_and_local_flag(...) -> None:
#     ...
#
# def test_install_remote_success_downloads_and_extracts(...) -> None:
#     ...
#
# def test_install_remote_missing_error_hints_sources(...) -> None:
#     ...
#
# def test_search_remote_lists_matches_with_source_label(...) -> None:
#     ...
#
# def test_search_default_prefers_local_then_falls_back_remote(...) -> None:
#     ...
#
# def test_list_remote_lists_latest_with_source_label(...) -> None:
#     ...
#
# def test_list_default_prefers_local_then_falls_back_remote(...) -> None:
#     ...
#
# def test_publish_requires_target_and_prints_default_target(...) -> None:
#     ...
